version: '3.8'
services:
  nodejs-api:
    build: .
    ports:
      - "8081:8081"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      # - "80:80"
      # - "443:443"
      - "3001:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - nodejs-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge